from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage
from typing import Iterable, Optional

from src.utils.logger import get_logger

logger = get_logger(__name__)


class EmailAlertService:
    """
    Sends production and AQI alerts through SMTP email.

    Required environment variables:
    - ALERT_SMTP_HOST
    - ALERT_SMTP_PORT
    - ALERT_SMTP_USERNAME
    - ALERT_SMTP_PASSWORD
    - ALERT_FROM_EMAIL
    - ALERT_TO_EMAILS

    ALERT_TO_EMAILS can contain multiple comma-separated addresses.
    """

    def __init__(self) -> None:
        self.smtp_host = os.getenv("ALERT_SMTP_HOST", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("ALERT_SMTP_PORT", "587"))

        self.smtp_username = os.getenv("ALERT_SMTP_USERNAME", "").strip()
        self.smtp_password = os.getenv("ALERT_SMTP_PASSWORD", "").strip()

        self.from_email = (
            os.getenv("ALERT_FROM_EMAIL", "").strip()
            or self.smtp_username
        )

        raw_recipients = os.getenv("ALERT_TO_EMAILS", "")
        self.default_recipients = [
            email.strip()
            for email in raw_recipients.split(",")
            if email.strip()
        ]

        self.use_tls = (
            os.getenv("ALERT_SMTP_USE_TLS", "true")
            .strip()
            .lower()
            in {"1", "true", "yes", "on"}
        )

    def _validate_configuration(
        self,
        recipients: Iterable[str],
    ) -> None:
        missing = []

        if not self.smtp_host:
            missing.append("ALERT_SMTP_HOST")

        if not self.smtp_username:
            missing.append("ALERT_SMTP_USERNAME")

        if not self.smtp_password:
            missing.append("ALERT_SMTP_PASSWORD")

        if not self.from_email:
            missing.append("ALERT_FROM_EMAIL")

        if not list(recipients):
            missing.append("ALERT_TO_EMAILS")

        if missing:
            raise ValueError(
                "Email alert configuration is incomplete. Missing: "
                + ", ".join(missing)
            )

    def send_alert(
        self,
        title: str,
        message: str,
        severity: str = "warning",
        recipients: Optional[list[str]] = None,
    ) -> bool:
        """
        Send one production alert email.

        Returns:
            True when successfully sent, otherwise False.
        """

        recipient_list = recipients or self.default_recipients

        try:
            self._validate_configuration(recipient_list)

            severity_clean = severity.strip().upper()

            email_message = EmailMessage()
            email_message["Subject"] = (
                f"[AQI MLOps][{severity_clean}] {title}"
            )
            email_message["From"] = self.from_email
            email_message["To"] = ", ".join(recipient_list)

            email_message.set_content(
                f"""
AQI Forecasting MLOps Alert

Severity: {severity_clean}
Title: {title}

Details:
{message}

This is an automated message generated by the AQI Forecasting MLOps platform.
""".strip()
            )

            with smtplib.SMTP(
                host=self.smtp_host,
                port=self.smtp_port,
                timeout=20,
            ) as smtp:
                if self.use_tls:
                    smtp.starttls()

                smtp.login(
                    self.smtp_username,
                    self.smtp_password,
                )

                smtp.send_message(email_message)

            logger.info(
                "Email alert sent | severity=%s | title=%s | recipients=%s",
                severity_clean,
                title,
                recipient_list,
            )

            return True

        except Exception as err:
            logger.exception(
                "Email alert sending failed | title=%s | error=%s",
                title,
                err,
            )
            return False