"""
Central configuration constants for the AQI Forecasting MLOps Pipeline.
"""

from pathlib import Path

# ------------------------------------------------------------------
# File System Paths
# ------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent
DATA_DIR = BASE_DIR / "data"
PROCESSED_DATA_DIR = DATA_DIR / "training"
MODELS_DIR = BASE_DIR / "models/registry"

# Parquet dataset path generated by Phase 4
TRAINING_DATASET_PATH = PROCESSED_DATA_DIR / "features_train.parquet"

# ------------------------------------------------------------------
# Column Schema
# ------------------------------------------------------------------
TARGET_COL = "aqi"
TIME_COL = "timestamp"
CITY_COL = "city"

# Pipeline Metadata Columns (to be excluded from Model Input X)
METADATA_COLUMNS = {
    TIME_COL,
    CITY_COL,
    "country",
    "created_at",
    "source",
    "aqi_category",
    "dominant_pollutant",
}

# ------------------------------------------------------------------
# Dataset Split Specifications (Phase 4 Split Metrics)
# ------------------------------------------------------------------
TRAIN_SIZE = 66550
VAL_SIZE = 14982
TEST_SIZE = 14849
EXPECTED_FEATURE_COUNT = 626